export const weybridgeDbs = [
  {
    id: 101,
    unitNo: "101",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10001",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 BR",
    balconyArea: "360.05",
    totalArea: "1136.67",
    price: "1,014,377.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 102,
    unitNo: "102",
    propertyName: "Weybridge Gardens",
    propertyNo: "P1002",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "185.68",
    totalArea: "682.54",
    price: "660,948.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 103,
    unitNo: "103",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10003",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "185.79",
    totalArea: "625.50",
    price: " 605,712.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 104,
    unitNo: "104",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10004",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Available",
    floor: "1",
    bedrooms: "1 BR",
    balconyArea: "250.91",
    totalArea: "984.80",
    price: " 887,463.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 105,
    unitNo: "105",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10005",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 736,041.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 106,
    unitNo: "106",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10006",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 485,713.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 107,
    unitNo: "107",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10007",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "177.97",
    totalArea: "893.73",
    price: " 821,033.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 108,
    unitNo: "108",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10008",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 816,486.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 109,
    unitNo: "109",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10009",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "117.00",
    totalArea: "864.02",
    price: " 778,621.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 110,
    unitNo: "110",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10010",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 520,086.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 111,
    unitNo: "111",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10011",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 593,663.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 112,
    unitNo: "112",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10012",
    type: "Residential",
    view: "Street & Community View",
    status: "Available",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 912,578.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 113,
    unitNo: "113",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10013",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 915,588.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 114,
    unitNo: "114",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10014",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "189.77",
    totalArea: "728.29",
    price: " 691,688.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 115,
    unitNo: "115",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10015",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "234.76",
    totalArea: "661.23",
    price: " 634,155.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 116,
    unitNo: "116",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10016",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "1",
    bedrooms: "Studio",
    balconyArea: "163.40",
    totalArea: "642.50",
    price: " 616,192.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 117,
    unitNo: "117",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10017",
    type: "Residential",
    view: "Street View",
    status: "Available",
    floor: "1",
    bedrooms: "1 Br",
    balconyArea: "355.42",
    totalArea: "1087.48",
    price: " 960,965.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 201,
    unitNo: "201",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10018",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 BR",
    balconyArea: "118.19",
    totalArea: "894.81",
    price: " 818,228.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 202,
    unitNo: "202",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10019",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "545.74",
    price: " 525,985.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 203,
    unitNo: "203",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10020",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 471,202.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 204,
    unitNo: "204",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10021",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 BR",
    balconyArea: "83.21",
    totalArea: "817.09",
    price: " 739,974.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 205,
    unitNo: "205",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10022",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 BR",
    balconyArea: "83.31",
    totalArea: "817.09",
    price: " 739,975.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 206,
    unitNo: "206",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10023",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "506.45",
    price: " 487,799.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 207,
    unitNo: "207",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10024",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "188.19",
    totalArea: "893.95",
    price: " 825,300.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 208,
    unitNo: "208",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10025",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "888.46",
    price: " 820,232.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 209,
    unitNo: "209",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10026",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "864.35",
    price: " 797,974.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 210,
    unitNo: "210",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10027",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "541.97",
    price: " 522,352.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 211,
    unitNo: "211",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10028",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "63.61",
    totalArea: "601.71",
    price: " 579,930.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 212,
    unitNo: "212",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10029",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "277..71",
    totalArea: "1012.89",
    price: " 917,296.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 213,
    unitNo: "213",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10030",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 920,121.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 214,
    unitNo: "214",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10031",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "62.31",
    totalArea: "600.85",
    price: " 579,100.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 215,
    unitNo: "215",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10032",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 464,321.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 216,
    unitNo: "216",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10033",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "48.65",
    totalArea: "527.76",
    price: " 508,657.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 217,
    unitNo: "217",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10034",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "1 Br",
    balconyArea: "116.25",
    totalArea: "848.31",
    price: " 768,249.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 301,
    unitNo: "301",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10035",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 BR",
    balconyArea: "117.97",
    totalArea: "894.59",
    price: " 814,152.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 302,
    unitNo: "302",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10036",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "546.06",
    price: " 528,886.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 303,
    unitNo: "303",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10037",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 473,524.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 304,
    unitNo: "304",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10038",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 BR",
    balconyArea: "82.88",
    totalArea: "816.77",
    price: " 743,329.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 305,
    unitNo: "305",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10039",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 757,762.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 306,
    unitNo: "306",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10040",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 490,522.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 307,
    unitNo: "307",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10041",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "117.97",
    totalArea: "893.73",
    price: " 813,369.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 308,
    unitNo: "308",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10042",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 808,864.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 309,
    unitNo: "309",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10043",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "117.11",
    totalArea: "864.13",
    price: " 786,430.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 310,
    unitNo: "310",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10044",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 525,235.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 311,
    unitNo: "311",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10045",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 582,573.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 312,
    unitNo: "312",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10046",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 921,614.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 313,
    unitNo: "313",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10047",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 924,654.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 314,
    unitNo: "314",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10048",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "62.65",
    totalArea: "601.17",
    price: " 582,263.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 315,
    unitNo: "315",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10049",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 464,620.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 316,
    unitNo: "316",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10050",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "Studio",
    balconyArea: "48.44",
    totalArea: "527.54",
    price: " 510,948.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 317,
    unitNo: "317",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10051",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "3",
    bedrooms: "1 Br",
    balconyArea: "116.57",
    totalArea: "848.63",
    price: " 772,324.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 401,
    unitNo: "401",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10052",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 BR",
    balconyArea: "118.19",
    totalArea: "894.81",
    price: " 826,289.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 402,
    unitNo: "402",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10053",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "545.74",
    price: " 531,167.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 403,
    unitNo: "403",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10054",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 475,845.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 404,
    unitNo: "404",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10055",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 BR",
    balconyArea: "83.21",
    totalArea: "817.09",
    price: " 761,775.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 405,
    unitNo: "405",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10056",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 BR",
    balconyArea: "83.31",
    totalArea: "817.09",
    price: " 761,775.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 406,
    unitNo: "406",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10057",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "506.12",
    price: " 492,605.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 407,
    unitNo: "407",
    propertyName: "Weybridge Gardens",
    propertyNo: "P1058",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "893.95",
    price: " 833,432.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 408,
    unitNo: "408",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10059",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "117.33",
    totalArea: "864.35",
    price: " 812,537.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 409,
    unitNo: "409",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10060",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "117.33",
    totalArea: "864.35",
    price: " 805,836.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 410,
    unitNo: "410",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10061",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "541.97",
    price: " 527,499.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 411,
    unitNo: "411",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10062",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "63.61",
    totalArea: "601.71",
    price: " 585,643.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 412,
    unitNo: "412",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10063",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "277.71",
    totalArea: "1012.89",
    price: " 926,333.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 413,
    unitNo: "413",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10064",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 911,144.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 414,
    unitNo: "414",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10065",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "62.32",
    totalArea: "600.85",
    price: " 596,161.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 415,
    unitNo: "415",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10066",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 464,918.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 416,
    unitNo: "416",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10067",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "4",
    bedrooms: "Studio",
    balconyArea: "48.65",
    totalArea: "527.76",
    price: " 513,668.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 417,
    unitNo: "417",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10068",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "4",
    bedrooms: "1 Br",
    balconyArea: "116.25",
    totalArea: "848.31",
    price: " 775,817.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 501,
    unitNo: "501",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10069",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 BR",
    balconyArea: "117.97",
    totalArea: "894.59",
    price: " 830,115.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 502,
    unitNo: "502",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10070",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "546.06",
    price: " 534,072.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 503,
    unitNo: "503",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10071",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 478,166.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 504,
    unitNo: "504",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10072",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 BR",
    balconyArea: "82.88",
    totalArea: "816.77",
    price: " 765,191.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 505,
    unitNo: "505",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10073",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 750,616.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 506,
    unitNo: "506",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10074",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 495,331.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 507,
    unitNo: "507",
    propertyName: "Weybridge Gardens",
    propertyNo: "P1075",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "117.97",
    totalArea: "893.73",
    price: " 821,343.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 508,
    unitNo: "508",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10076",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 832,654.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 509,
    unitNo: "509",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10077",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "117.11",
    totalArea: "864.13",
    price: " 794,141.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 510,
    unitNo: "510",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10077",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 530,385.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 511,
    unitNo: "511",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10078",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 588,285.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 512,
    unitNo: "512",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10080",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 912,579.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 513,
    unitNo: "513",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10081",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 915,589.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 514,
    unitNo: "514",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10082",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "62.65",
    totalArea: "601.17",
    price: " 599,389.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 515,
    unitNo: "515",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10082",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 465,217.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 516,
    unitNo: "516",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10084",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "48.44",
    totalArea: "527.54",
    price: " 515,958.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 517,
    unitNo: "517",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10085",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "5",
    bedrooms: "1 Br",
    balconyArea: "116.57",
    totalArea: "848.63",
    price: " 779,896.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 601,
    unitNo: "601",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10086",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 BR",
    balconyArea: "118.19",
    totalArea: "894.81",
    price: " 826,327.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 602,
    unitNo: "602",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10087",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "545.74",
    price: " 536,349.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 603,
    unitNo: "603",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10088",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 480,487.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 604,
    unitNo: "604",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10089",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 BR",
    balconyArea: "83.21",
    totalArea: "817.09",
    price: " 754,556.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 605,
    unitNo: "605",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10090",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 BR",
    balconyArea: "83.31",
    totalArea: "817.09",
    price: " 769,207.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 606,
    unitNo: "606",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10091",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "506.12",
    price: " 497,411.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 607,
    unitNo: "607",
    propertyName: "Weybridge Gardens",
    propertyNo: "P1092",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "893.95",
    price: " 825,533.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 608,
    unitNo: "608",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10093",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "888.46",
    price: " 836,395.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 609,
    unitNo: "609",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10094",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "117.33",
    totalArea: "864.35",
    price: " 798,199.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 610,
    unitNo: "610",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10094",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "541.97",
    price: " 532,644.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 611,
    unitNo: "611",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10078",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "601.71",
    price: " 591,356.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 612,
    unitNo: "612",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10097",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "277.71",
    totalArea: "1012.89",
    price: " 917,208.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 613,
    unitNo: "613",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10098",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 920,033.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 614,
    unitNo: "614",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10099",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "62.32",
    totalArea: "600.85",
    price: " 601,977.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 615,
    unitNo: "615",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10100",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 467,475.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 616,
    unitNo: "616",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10101",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "6",
    bedrooms: "Studio",
    balconyArea: "48.65",
    totalArea: "527.76",
    price: " 518,679.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 617,
    unitNo: "617",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10102",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "6",
    bedrooms: "1 Br",
    balconyArea: "116.25",
    totalArea: "848.31",
    price: " 783,387.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 701,
    unitNo: "701",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10103",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 BR",
    balconyArea: "117.97",
    totalArea: "894.59",
    price: " 830,115.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 702,
    unitNo: "702",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10104",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "546.06",
    price: " 539,257.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 703,
    unitNo: "703",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10105",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 482,808.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 704,
    unitNo: "704",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10106",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 BR",
    balconyArea: "82.88",
    totalArea: "816.77",
    price: " 757,904.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 705,
    unitNo: "705",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10107",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 757,904.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 706,
    unitNo: "706",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10108",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 500,141.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 707,
    unitNo: "707",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10109",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "117.97",
    totalArea: "893.73",
    price: " 845,421.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 708,
    unitNo: "708",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10110",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 840,738.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 709,
    unitNo: "709",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10111",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "117.11",
    totalArea: "864.13",
    price: " 801,850.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 710,
    unitNo: "710",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10112",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 535,534.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 711,
    unitNo: "711",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10113",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 593,996.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 712,
    unitNo: "712",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10114",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 921,438.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 713,
    unitNo: "713",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10115",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 924,477.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 714,
    unitNo: "714",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10116",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "62.65",
    totalArea: "601.17",
    price: " 593,680.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 715,
    unitNo: "715",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10117",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 469,733.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 716,
    unitNo: "716",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10118",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "48.44",
    totalArea: "527.54",
    price: " 520,967.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 717,
    unitNo: "717",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10120",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "7",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "848.81",
    price: " 787,467.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 801,
    unitNo: "801",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10120",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 BR",
    balconyArea: "118.19",
    totalArea: "894.81",
    price: " 870,238.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 802,
    unitNo: "802",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10121",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 564,851.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 803,
    unitNo: "803",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10122",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 506,020.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 804,
    unitNo: "804",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10106",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 BR",
    balconyArea: "83.21",
    totalArea: "817.09",
    price: " 794,653.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 805,
    unitNo: "805",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10124",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 BR",
    balconyArea: "83.31",
    totalArea: "817.09",
    price: " 794,653.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 806,
    unitNo: "806",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10125",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "506.12",
    price: " 523,844.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 807,
    unitNo: "807",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10126",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "893.95",
    price: " 869,402.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 808,
    unitNo: "808",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10127",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "888.46",
    price: " 864,063.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 809,
    unitNo: "809",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10128",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "117.33",
    totalArea: "864.35",
    price: " 840,615.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 810,
    unitNo: "810",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10129",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "541.97",
    price: " 560,949.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 811,
    unitNo: "811",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10130",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "63.61",
    totalArea: "601.71",
    price: " 634,874.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 812,
    unitNo: "812",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10131",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "277.71",
    totalArea: "1012.89",
    price: " 965,948.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 813,
    unitNo: "813",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10132",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 968,924.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 814,
    unitNo: "814",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10133",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "62.32",
    totalArea: "600.85",
    price: " 621,891.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 815,
    unitNo: "815",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10134",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 492,317.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 816,
    unitNo: "816",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10135",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "48.65",
    totalArea: "527.76",
    price: " 546,241.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 817,
    unitNo: "817",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10136",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "8",
    bedrooms: "1 Br",
    balconyArea: "116.25",
    totalArea: "848.31",
    price: " 825,015.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 901,
    unitNo: "901",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10137",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 BR",
    balconyArea: "117.97",
    totalArea: "894.59",
    price: " 909,933.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 902,
    unitNo: "902",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10138",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "546.06",
    price: " 591,108.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 903,
    unitNo: "903",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10139",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 529,232.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 904,
    unitNo: "904",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10140",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 BR",
    balconyArea: "82.88",
    totalArea: "816.77",
    price: " 830,779.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 905,
    unitNo: "905",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10141",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 830,779.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 906,
    unitNo: "906",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10142",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 548,230.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 907,
    unitNo: "907",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10143",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "117.97",
    totalArea: "893.73",
    price: " 909,059.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 908,
    unitNo: "908",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10144",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 904,024.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 909,
    unitNo: "909",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10145",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "117.11",
    totalArea: "864.13",
    price: " 878,951.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 910,
    unitNo: "910",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10146",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 587,027.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 911,
    unitNo: "911",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10147",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 651,111.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 912,
    unitNo: "912",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10148",
    type: "Residential",
    view: "Street & Community View",
    status: "Available",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 1,010,038.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 913,
    unitNo: "913",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10149",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 1,013,370.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 914,
    unitNo: "914",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10150",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "62.65",
    totalArea: "601.17",
    price: " 650,765.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 915,
    unitNo: "915",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10151",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 514,901.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 916,
    unitNo: "916",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10152",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "9",
    bedrooms: "Studio",
    balconyArea: "48.44",
    totalArea: "527.54",
    price: " 571,060.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 917,
    unitNo: "917",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10153",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "9",
    bedrooms: "1 Br",
    balconyArea: "116.57",
    totalArea: "848.63",
    price: " 863,186.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 1001,
    unitNo: "1001",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10154",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 BR",
    balconyArea: "118.19",
    totalArea: "894.81",
    price: " 931,629.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 1002,
    unitNo: "1002",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10155",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "545.74",
    price: " 616,673.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 1003,
    unitNo: "1003",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10156",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 552,444.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 1004,
    unitNo: "1004",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10157",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 BR",
    balconyArea: "83.21",
    totalArea: "817.09",
    price: " 867,557.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 1005,
    unitNo: "1005",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10158",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 BR",
    balconyArea: "83.31",
    totalArea: "817.09",
    price: " 867,557.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 1006,
    unitNo: "1006",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10159",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "48.87",
    totalArea: "506.12",
    price: " 571,903.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 1007,
    unitNo: "1007",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10160",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "893.95",
    price: " 949,164.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 1008,
    unitNo: "1008",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10161",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "118.19",
    totalArea: "888.46",
    price: " 925,017.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 1009,
    unitNo: "1009",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10162",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "117.33",
    totalArea: "864.35",
    price: " 917,736.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 1010,
    unitNo: "1010",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10163",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "44.24",
    totalArea: "541.97",
    price: " 612,413.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 1011,
    unitNo: "1011",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10164",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "63.61",
    totalArea: "601.71",
    price: " 679,917.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 1012,
    unitNo: "1012",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10165",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "277.71",
    totalArea: "1012.89",
    price: " 1,054,567.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 1013,
    unitNo: "1013",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10166",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 1,057,816.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 1014,
    unitNo: "1014",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10167",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "62.32",
    totalArea: "600.85",
    price: " 678,946.00 ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 1015,
    unitNo: "1015",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10168",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: " 537,484.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 1016,
    unitNo: "1016",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10169",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "10",
    bedrooms: "Studio",
    balconyArea: "48.65",
    totalArea: "527.76",
    price: " 596,355.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 1017,
    unitNo: "1017",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10170",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "10",
    bedrooms: "1 Br",
    balconyArea: "116.25",
    totalArea: "848.59",
    price: " 900,705.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
  {
    id: 1101,
    unitNo: "1101",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10171",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 BR",
    balconyArea: "117.97",
    totalArea: "894.59",
    price: " 980,143.00 ",
    imageURL: "/assets/images/wey-units/unit1.png",
  },
  {
    id: 1102,
    unitNo: "1102",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10172",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "546.06",
    price: " 649,202.00 ",
    imageURL: "/assets/images/wey-units/unit2.png",
  },
  {
    id: 1103,
    unitNo: "1103",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10173",
    type: "Residential",
    view: "Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "488.90",
    price: " 592,423.00 ",
    imageURL: "/assets/images/wey-units/unit3.png",
  },
  {
    id: 1104,
    unitNo: "1104",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10174",
    type: "Residential",
    view: "Polo Club & Community View",
    status: "Available",
    floor: "11",
    bedrooms: "1 BR",
    balconyArea: "82.88",
    totalArea: "816.77",
    price: " 912,427.00 ",
    imageURL: "/assets/images/wey-units/unit4.png",
  },
  {
    id: 1105,
    unitNo: "1105",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10175",
    type: "Residential",
    view: "Polo Club 7 Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 BR",
    balconyArea: "82.99",
    totalArea: "816.77",
    price: " 912,427.00 ",
    imageURL: "/assets/images/wey-units/unit5.png",
  },
  {
    id: 1106,
    unitNo: "1106",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10176",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "506.45",
    price: " 613,689.00 ",
    imageURL: "/assets/images/wey-units/unit6.png",
  },
  {
    id: 1107,
    unitNo: "1107",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10177",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "117.97",
    totalArea: "893.73",
    price: " 979,201.00 ",
    imageURL: "/assets/images/wey-units/unit7.png",
  },
  {
    id: 1108,
    unitNo: "1108",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10178",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "118.51",
    totalArea: "888.78",
    price: " 973,777.00 ",
    imageURL: "/assets/images/wey-units/unit8.png",
  },
  {
    id: 1109,
    unitNo: "1109",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10179",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "117.11",
    totalArea: "864.13",
    price: " 946,770.00 ",
    imageURL: "/assets/images/wey-units/unit9.png",
  },
  {
    id: 1110,
    unitNo: "1110",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10180",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "44.56",
    totalArea: "542.29",
    price: " 644,719.00 ",
    imageURL: "/assets/images/wey-units/unit10.png",
  },
  {
    id: 1111,
    unitNo: "1111",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10164",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "63.40",
    totalArea: "601.49",
    price: " 694,473.00 ",
    imageURL: "/assets/images/wey-units/unit11.png",
  },
  {
    id: 1012,
    unitNo: "1012",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10182",
    type: "Residential",
    view: "Street & Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "277.49",
    totalArea: "1012.67",
    price: " 1,109,515.00 ",
    imageURL: "/assets/images/wey-units/unit12.png",
  },
  {
    id: 1113,
    unitNo: "1113",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10183",
    type: "Residential",
    view: "Street & Community View",
    status: "Available",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "280.51",
    totalArea: "1016.01",
    price: " 1,113,175.00 ",
    imageURL: "/assets/images/wey-units/unit13.png",
  },
  {
    id: 1114,
    unitNo: "1114",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10167",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "62.65",
    totalArea: "601.17",
    price: "  694,104.00  ",
    imageURL: "/assets/images/wey-units/unit14.png",
  },
  {
    id: 1115,
    unitNo: "1115",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10185",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "49.19",
    totalArea: "475.66",
    price: "  576,379.00 ",
    imageURL: "/assets/images/wey-units/unit15.png",
  },
  {
    id: 1116,
    unitNo: "1116",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10186",
    type: "Residential",
    view: "Street View",
    status: "Available",
    floor: "11",
    bedrooms: "Studio",
    balconyArea: "48.44",
    totalArea: "527.54",
    price: " 627,183.00 ",
    imageURL: "/assets/images/wey-units/unit16.png",
  },
  {
    id: 1117,
    unitNo: "1117",
    propertyName: "Weybridge Gardens",
    propertyNo: "P10187",
    type: "Residential",
    view: "Street View",
    status: "Sold",
    floor: "11",
    bedrooms: "1 Br",
    balconyArea: "116.57",
    totalArea: "848.63",
    price: " 929,788.00 ",
    imageURL: "/assets/images/wey-units/unit17.png",
  },
];