export const weybridgeDb2s = [
  {
    id: 103,
    unitNo: "WG2-103",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: "436,257.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 104,
    unitNo: "WG2-104",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 593,084.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 105,
    unitNo: "WG2-105",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 593,502.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 106,
    unitNo: "WG2-106",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 594,496.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 107,
    unitNo: "WG2-107",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 969,989.00 ",
    imageURL: "/assets/images/wey2-units/studio-3.jpg",
  },
  {
    id: 108,
    unitNo: "WG2-108",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 969,130.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 110,
    unitNo: "WG2-110",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 594,208.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },

  {
    id: 111,
    unitNo: "WG2-111",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "1",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: "431,980.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 115,
    unitNo: "WG2-110",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 627,943.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 117,
    unitNo: "WG2-117",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: " 593,502.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 119,
    unitNo: "WG2-119",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 967,286.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 120,
    unitNo: "WG2-120",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: "968,145.00",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 121,
    unitNo: "WG2-121",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 592,666.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 123,
    unitNo: "WG2-123",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "1",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 596,540.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 202,
    unitNo: "WG2-202",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Community/Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "2BR-TYPE 1",
    balconyArea: "1100.72 sq ft",
    totalArea: " 1,033,524.00 sq ft",
    price: " 1,033,524.00 ",
    imageURL: "/assets/images/wey2-units/2BR-01.jpg",
  },
  {
    id: 203,
    unitNo: "WG2-203",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "2",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: "438,396.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 204,
    unitNo: "WG2-204",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83",
    totalArea: "453.70",
    price: " 596,020.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 205,
    unitNo: "WG2-205",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 596,020.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 206,
    unitNo: "WG2-206",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 597,439.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 208,
    unitNo: "WG2-208",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 973,928.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 210,
    unitNo: "WG2-210",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 597,150.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 211,
    unitNo: "WG2-211",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Sold",
    floor: "2",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: "434,119.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 214,
    unitNo: "WG2-214",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 629,217.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 215,
    unitNo: "WG2-215",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: "630,962.00",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 217,
    unitNo: "WG2-217",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: "596,440.00",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 218,
    unitNo: "WG2-218",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: "597,294.00",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 220,
    unitNo: "WG2-220",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: "972,938.00",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 221,
    unitNo: "WG2-221",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 595,599.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 222,
    unitNo: "WG2-222",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 595,875.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 223,
    unitNo: "WG2-223",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "2",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 599,464.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 303,
    unitNo: "WG2-303",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "3",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: "440,534.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 305,
    unitNo: "WG2-305",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 599,378.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 306,
    unitNo: "WG2-306",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Availble",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: "600,382.00",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 307,
    unitNo: "WG2-307",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Availble",
    floor: "3",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 979,593.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 309,
    unitNo: "WG2-309",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Availble",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 599,233.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 310,
    unitNo: "WG2-310",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Availble",
    floor: "3",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 600,091.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 311,
    unitNo: "WG2-311",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "3",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "436,257.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 314,
    unitNo: "WG2-314",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 632,228.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 315,
    unitNo: "WG2-315",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 633,981.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 317,
    unitNo: "WG2-317",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: " 599,378.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 318,
    unitNo: "WG2-318",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 600,236.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 322,
    unitNo: "WG2-322",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 598,811.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 323,
    unitNo: "WG2-323",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "3",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 602,388.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 403,
    unitNo: "WG2-403",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "4",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "442,673.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 404,
    unitNo: "WG2-404",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 601,892.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 406,
    unitNo: "WG2-406",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 603,325.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 407,
    unitNo: "WG2-407",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 984,395.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 409,
    unitNo: "WG2-409",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 602,171.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 410,
    unitNo: "WG2-410",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 603,033.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 411,
    unitNo: "WG2-411",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "4",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "438,396.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 414,
    unitNo: "WG2-414",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 635,238.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 415,
    unitNo: "WG2-415",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 637,000.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 417,
    unitNo: "WG2-417",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: " 602,317.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 418,
    unitNo: "WG2-418",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 603,179.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 420,
    unitNo: "WG2-420",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 982,523.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 421,
    unitNo: "WG2-421",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 601,467.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 422,
    unitNo: "WG2-422",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 601,467.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 423,
    unitNo: "WG2-423",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "4",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 605,313.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 503,
    unitNo: "WG2-503",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "5",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: " 444,811.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 504,
    unitNo: "WG2-503",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 604,828.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 505,
    unitNo: "WG2-505",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 605,255.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 506,
    unitNo: "WG2-506",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 606,268.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 507,
    unitNo: "WG2-507",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 989,197.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 508,
    unitNo: "WG2-508",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 988,321.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 509,
    unitNo: "WG2-509",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 605,108.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 510,
    unitNo: "WG2-510",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 605,975.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 511,
    unitNo: "WG2-511",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "5",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: " 440,534.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 514,
    unitNo: "WG2-514",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 638,249.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 515,
    unitNo: "WG2-515",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 640,019.00  ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 519,
    unitNo: "WG2-519",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 986,440.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 520,
    unitNo: "WG2-520",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 987,316.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 521,
    unitNo: "WG2-521",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE-2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 604,401.00 ",
    imageURL: "/assets/images/wey2-units/studio-11.jpg",
  },
  {
    id: 522,
    unitNo: "WG2-522",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "5",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 604,681.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 603,
    unitNo: "WG2-603",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "6",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: " 446,950.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 606,
    unitNo: "WG2-606",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 609,211.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 607,
    unitNo: "WG2-607",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: "993,999.00",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 608,
    unitNo: "WG2-608",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 993,118.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 609,
    unitNo: "WG2-609",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 608,045.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 610,
    unitNo: "WG2-610",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 608,916.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 611,
    unitNo: "WG2-611",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "6",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: " 442,673.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 614,
    unitNo: "WG2-614",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 641,260.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 615,
    unitNo: "WG2-615",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 643,038.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 618,
    unitNo: "WG2-618",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 609,063.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 620,
    unitNo: "WG2-620",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 992,109.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 621,
    unitNo: "WG2-621",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 607,335.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 622,
    unitNo: "WG2-622",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 607,617.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 623,
    unitNo: "WG2-622",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "6",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "451.87 sq ft",
    price: " 611,161.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 703,
    unitNo: "WG2-703",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "7",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "449,088.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 704,
    unitNo: "WG2-704",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 610,700.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 707,
    unitNo: "WG2-707",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 998,800.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 708,
    unitNo: "WG2-708",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 997,916.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 709,
    unitNo: "WG2-709",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 610,983.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 711,
    unitNo: "WG2-711",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "7",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "444,811.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 714,
    unitNo: "WG2-714",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 644,270.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 715,
    unitNo: "WG2-715",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 646,057.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 718,
    unitNo: "WG2-718",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 612,006.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 719,
    unitNo: "WG2-719",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 996,017.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 720,
    unitNo: "WG2-720",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 996,902.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 721,
    unitNo: "WG2-721",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 610,269.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 722,
    unitNo: "WG2-722",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 610,552.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 723,
    unitNo: "WG2-723",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "7",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 614,085.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 724,
    unitNo: "WG2-724",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Community/Street View",
    status: "Block",
    floor: "7",
    bedrooms: "2BR-TYPE 3",
    balconyArea: "366.08 sq ft",
    totalArea: "1131.50 sq ft",
    price: " 1,088,087.00 ",
    imageURL: "/assets/images/wey2-units/2BR-03.jpg",
  },
  {
    id: 803,
    unitNo: "WG2-803",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "8",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: " 451,227.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 804,
    unitNo: "WG2-804",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: "  613,636.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 805,
    unitNo: "WG2-805",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 614,069.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 806,
    unitNo: "WG2-806",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 615,097.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 807,
    unitNo: "WG2-807",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 1,003,602.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 808,
    unitNo: "WG2-808",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 1,002,714.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 810,
    unitNo: "WG2-810",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 1,002,714.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 811,
    unitNo: "WG2-811",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "8",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05",
    totalArea: "353.59",
    price: " 446,950.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 815,
    unitNo: "WG2-815",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 649,076.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 818,
    unitNo: "WG2-818",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 614,948.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 819,
    unitNo: "WG2-819",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 1,000,806.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 820,
    unitNo: "WG2-820",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 1,001,695.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 821,
    unitNo: "WG2-821",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 613,203.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 822,
    unitNo: "WG2-822",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 613,487.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 823,
    unitNo: "WG2-823",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "8",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 617,010.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 903,
    unitNo: "WG2-903",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "9",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "  453,365.00  ",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 904,
    unitNo: "WG2-903",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 616,572.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 905,
    unitNo: "WG2-905",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 617,007.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 906,
    unitNo: "WG2-906",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 618,040.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 907,
    unitNo: "WG2-907",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 1,008,404.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 908,
    unitNo: "WG2-908",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 1,007,511.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 909,
    unitNo: "WG2-909",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "453.91",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 616,858.00 ",
    imageURL: "/assets/images/wey2-units/studio-3.jpg",
  },
  {
    id: 910,
    unitNo: "WG2-909",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 617,741.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 911,
    unitNo: "WG2-911",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "9",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "  449,088.00  ",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 914,
    unitNo: "WG2-914",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 650,291.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 915,
    unitNo: "WG2-915",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 652,095.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 917,
    unitNo: "WG2-917",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: " 617,007.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 918,
    unitNo: "WG2-918",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 617,890.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 919,
    unitNo: "WG2-919",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 1,005,594.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 920,
    unitNo: "WG2-920",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 1,006,487.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 921,
    unitNo: "WG2-921",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 616,137.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 922,
    unitNo: "WG2-922",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 616,423.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 923,
    unitNo: "WG2-923",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "9",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 619,934.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1001,
    unitNo: "WG2-1001",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Community/Street View",
    status: "Available",
    floor: "10",
    bedrooms: "1BR-TYPE 1",
    balconyArea: "170.82 sq ft",
    totalArea: "723.55 sq ft",
    price: " 882,044.00 ",
    imageURL: "/assets/images/wey2-units/1BR-01.jpg",
  },
  {
    id: 1003,
    unitNo: "WG2-1003",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "10",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "   455,504.00   ",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 1004,
    unitNo: "WG2-1004",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.83 sq ft",
    totalArea: "453.70 sq ft",
    price: " 619,508.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1005,
    unitNo: "WG2-1005",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.73 sq ft",
    totalArea: "454.02 sq ft",
    price: " 619,945.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1006,
    unitNo: "WG2-1006",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.78 sq ft",
    price: " 620,983.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1007,
    unitNo: "WG2-1007",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "129.27 sq ft",
    totalArea: "846.90 sq ft",
    price: " 1,013,206.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 1008,
    unitNo: "WG2-1008",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "129.27 sq ft",
    totalArea: "846.15 sq ft",
    price: " 1,012,309.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 1009,
    unitNo: "WG2-1009",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.83 sq ft",
    totalArea: "453.91 sq ft",
    price: " 619,795.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1010,
    unitNo: "WG2-1010",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.73 sq ft",
    totalArea: "454.56 sq ft",
    price: " 620,683.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1011,
    unitNo: "WG2-1011",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "10",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "  451,227.00  ",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 1014,
    unitNo: "WG2-1014",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "100.64 sq ft",
    totalArea: "465.22 sq ft",
    price: " 653,302.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1015,
    unitNo: "WG2-1015",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Villa/Street View",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "101.72 sq ft",
    totalArea: "466.51 sq ft",
    price: " 655,114.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1017,
    unitNo: "WG2-1017",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "454.02 sq ft",
    price: " 619,945.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1018,
    unitNo: "WG2-1018",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "454.67 sq ft",
    price: " 620,833.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1019,
    unitNo: "WG2-1018",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "1BR-TYPE 2",
    balconyArea: "128.95 sq ft",
    totalArea: "844.54 sq ft",
    price: " 1,010,383.00 ",
    imageURL: "/assets/images/wey2-units/1BR-02.jpg",
  },
  {
    id: 1020,
    unitNo: "WG2-1020",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "1BR-TYPE 3",
    balconyArea: "128.95 sq ft",
    totalArea: "845.29 sq ft",
    price: " 1,011,280.00 ",
    imageURL: "/assets/images/wey2-units/1BR-03.jpg",
  },
  {
    id: 1021,
    unitNo: "WG2-1021",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "453.38 sq ft",
    price: " 619,071.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1022,
    unitNo: "WG2-1022",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 1",
    balconyArea: "87.62 sq ft",
    totalArea: "453.59 sq ft",
    price: " 619,358.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-01.jpg",
  },
  {
    id: 1023,
    unitNo: "WG2-1023",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Available",
    floor: "10",
    bedrooms: "ST-TYPE 2",
    balconyArea: "87.62 sq ft",
    totalArea: "451.87 sq ft",
    price: " 622,858.00 ",
    imageURL: "/assets/images/wey2-units/ST-Type-02.jpg",
  },
  {
    id: 1103,
    unitNo: "WG2-1103",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "11",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "457,642.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 1111,
    unitNo: "WG2-1111",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "11",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "453,365.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
  {
    id: 1203,
    unitNo: "WG2-1203",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Partial Community View",
    status: "Sold",
    floor: "12",
    bedrooms: "ST-TYPE 3",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "459,781.00",
    imageURL: "/assets/images/wey2-units/ST-Type-03.jpg",
  },
  {
    id: 1211,
    unitNo: "WG2-1211",
    propertyName: "Weybridge Gardens 2",
    propertyNo: "P10001",
    type: "Residential",
    view: "Not Applicable",
    status: "Sold",
    floor: "12",
    bedrooms: "ST-TYPE 4",
    balconyArea: "360.05 sq ft",
    totalArea: "353.59 sq ft",
    price: "455,504.00",
    imageURL: "/assets/images/wey2-units/ST-Type-04.jpg",
  },
];
